---
excludes:
  scopes:
    - pattern: "dev"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
    - pattern: "lint"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for static code analysis only."
    - pattern: "test"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
license_choices:
  repository_license_choices:
    - given: FTL OR GPL-2.0-or-later
      choice: FTL
resolutions:
  rule_violations:
    - message: ".*PyPI::anyio:4\\.12\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/agronholm/anyio/blob/4.12.1/LICENSE"
    - message: ".*PyPI::click:8\\.3\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pallets/click/blob/8.3.1/LICENSE.txt"
    - message: ".*PyPI::fsspec:2024\\.12\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/fsspec/filesystem_spec/blob/2024.12.0/LICENSE"
    - message: ".*PyPI::httpcore:1\\.0\\.9.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/encode/httpcore/blob/master/LICENSE.md"
    - message: ".*PyPI::idna:3\\.11.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/kjd/idna/blob/v3.11/LICENSE.md"
    - message: ".*PyPI::joblib:1\\.5\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/joblib/joblib/blob/1.5.3/LICENSE.txt"
    - message: ".*PyPI::more-itertools:10\\.8\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/more-itertools/more-itertools/blob/v10.8.0/LICENSE"
    - message: ".*PyPI::numpy:2\\.4\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/numpy/numpy/blob/v2.4.2/LICENSE.txt"
    - message: ".*PyPI::packaging:25\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache-2.0 license: https://github.com/pypa/packaging/blob/25.0/LICENSE.APACHE"
    - message: ".*PyPI::pandas:2\\.3\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pandas-dev/pandas/blob/2.3.x/LICENSE"
    - message: ".*PyPI::pyarrow:23\\.0\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache-2.0 license: https://github.com/apache/arrow/blob/apache-arrow-23.0.0/LICENSE.txt"
    - message: ".*PyPI::pydantic-core:2\\.41\\.5.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/pydantic-core/blob/v2.41.5/LICENSE"
    - message: ".*PyPI::pydantic:2\\.12\\.5.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/pydantic/blob/v2.12.5/LICENSE"
    - message: ".*PyPI::python-dateutil:2\\.9\\.0\\.post0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache-2.0 license: https://github.com/dateutil/dateutil/blob/master/LICENSE"
    - message: ".*PyPI::regex:2026\\.1\\.15.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache-2.0 license: https://github.com/mrabarnett/mrab-regex/blob/2026.1.15/LICENSE.txt"
    - message: ".*PyPI::typing-extensions:4\\.15\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Python Software Foundation License Version 2: https://github.com/python/typing_extensions/blob/4.15.0/LICENSE"
    - message: ".*PyPI::typing-inspection:0\\.4\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/typing-inspection/blob/v0.4.2/LICENSE"
    - message: ".*PyPI::urllib3:2\\.6\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/urllib3/urllib3/blob/2.6.3/LICENSE.txt"
    - message: ".*PyPI::uuid-utils:0\\.14\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/aminalaee/uuid-utils/blob/0.14.0/LICENSE.md"
    - message: ".*PyPI::zstandard:0\\.25\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/indygreg/python-zstandard/blob/0.25.0/LICENSE"
