name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  run_tests:
    uses: epam/ai-dial-ci/.github/workflows/python_package_pr.yml@2.0.1
    secrets: inherit
    with:
      python-version: 3.11
      code-checks-python-versions: '["3.9", "3.10", "3.11", "3.12"]'
