name: Release Workflow

on:
  push:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/python_package_release.yml@2.4.1
    secrets: inherit
    with:
      python-version: 3.11
      code-checks-python-versions: '["3.9", "3.10", "3.11", "3.12"]'
